import type { HaasMachineProfile } from './types';

export const HAAS_MACHINE_PROFILES: HaasMachineProfile[] = [
  {
    id: 'haas_vf2',
    name: 'Haas VF-2 (Centro de Maquinado VMC)',
    type: 'mill',
    description: 'Centro vertical estándar de 3 ejes, 30" x 16" x 20" recorrido.',
    maxRpm: 8100,
    horsepower: 30,
    kw: 22.4,
    maxTorqueNm: 122,
    taperOrSpindle: 'CAT40',
    chuckOrTableSize: '36" x 14" Mesa',
    notes: 'Tirante Haas 45° con rosca 5/8"-11 UNC. Cono CAT40 balanceado a 8,100 RPM.',
  },
  {
    id: 'haas_vf3',
    name: 'Haas VF-3 (Centro de Maquinado VMC)',
    type: 'mill',
    description: 'Centro vertical de capacidad extendida, 40" x 20" x 25" recorrido.',
    maxRpm: 8100,
    horsepower: 30,
    kw: 22.4,
    maxTorqueNm: 122,
    taperOrSpindle: 'CAT40',
    chuckOrTableSize: '48" x 18" Mesa',
    notes: 'Ideal para piezas largas y ensambles. Mismo husillo directo en línea que VF-2.',
  },
  {
    id: 'haas_mini_mill',
    name: 'Haas Mini Mill (VMC Compacto)',
    type: 'mill',
    description: 'Fresadora compacta para prototipos y segundas operaciones, 16" x 12" x 10".',
    maxRpm: 6000,
    horsepower: 10,
    kw: 7.5,
    maxTorqueNm: 45,
    taperOrSpindle: 'CAT40',
    chuckOrTableSize: '28.75" x 12" Mesa',
    notes: 'Potencia limitada (10 HP). Mantener profundidades de corte moderadas (ap < 3mm en acero).',
  },
  {
    id: 'haas_st10',
    name: 'Haas ST-10 (Torno CNC Compacto)',
    type: 'lathe',
    description: 'Torno CNC para piezas pequeñas y barras de hasta 1.75" (44 mm).',
    maxRpm: 6000,
    horsepower: 15,
    kw: 11.2,
    taperOrSpindle: 'A2-5 (Chuck 6.5")',
    chuckOrTableSize: 'Chuck 6.5" (165 mm)',
    barCapacityInch: 1.75,
    notes: 'Torreta acepta zancos exteriores de 3/4" (19.05 mm) y barras de mandrinar de 1" con buje.',
  },
  {
    id: 'haas_st20',
    name: 'Haas ST-20 (Torno CNC de Producción)',
    type: 'lathe',
    description: 'Torno CNC estándar de taller, volteo de 13" x 21", barra de 2.50" (64 mm).',
    maxRpm: 4000,
    horsepower: 20,
    kw: 14.9,
    taperOrSpindle: 'A2-6 (Chuck 8.3")',
    chuckOrTableSize: 'Chuck 8.3" (210 mm)',
    barCapacityInch: 2.50,
    notes: 'Torreta acepta zancos exteriores de 1" (25.4 mm / 25x25) y barras de 1.25" y 1" con bujes.',
  },
  {
    id: 'haas_st30',
    name: 'Haas ST-30 (Torno CNC Pesado)',
    type: 'lathe',
    description: 'Torno CNC de alta capacidad para flechas pesadas, barra de 3.00" (76 mm).',
    maxRpm: 3400,
    horsepower: 30,
    kw: 22.4,
    taperOrSpindle: 'A2-8 (Chuck 10")',
    chuckOrTableSize: 'Chuck 10" (254 mm)',
    barCapacityInch: 3.00,
    notes: 'Torreta pesada de zancos de 1" o 1.25". Alta rigidez para desbaste agresivo de barras 4140.',
  }
];

export function findHaasMachineById(id: string): HaasMachineProfile | undefined {
  return HAAS_MACHINE_PROFILES.find(m => m.id === id);
}
