import type { MaterialSpec } from './types';

export const MATERIAL_DATABASE: MaterialSpec[] = [
  {
    id: 'steel_4140',
    name: 'Acero Aleado 4140 / 4140T',
    category: 'Aceros de Media Aleación',
    group: 'P',
    description: 'Acero tratado al cromo-molibdeno común en flechas, pernos y bujes de alta resistencia.',
    vcTurningMMin: [160, 260],
    sfmMilling: [250, 450],
    kc: 2100,
    recommendedChipLoadInch: [0.002, 0.0045],
    recommendedFeedTurningMm: [0.25, 0.08],
    hardnessTypical: '28-34 HRC (Pre-tratado)',
    chipCharacteristics: 'Viruta en espiral continua o fragmentada con rompevirutas adecuado. Requiere filo tenaz.',
  },
  {
    id: 'steel_1018',
    name: 'Acero al Carbón 1018 / 1020 (CRS/HRS)',
    category: 'Aceros al Bajo Carbón',
    group: 'P',
    description: 'Acero dulce suave y dúctil para piezas estructurales, placas y fixtures.',
    vcTurningMMin: [200, 320],
    sfmMilling: [400, 650],
    kc: 1800,
    recommendedChipLoadInch: [0.0025, 0.005],
    recommendedFeedTurningMm: [0.30, 0.10],
    hardnessTypical: '120-160 HB',
    chipCharacteristics: 'Tiende a formar viruta larga y gomosa. Requiere rompevirutas agresivo para evitar enredos.',
  },
  {
    id: 'steel_1045',
    name: 'Acero al Medio Carbón 1045',
    category: 'Aceros al Medio Carbón',
    group: 'P',
    description: 'Acero de maquinaria para engranes, flechas y pernos de resistencia media.',
    vcTurningMMin: [180, 280],
    sfmMilling: [300, 500],
    kc: 1950,
    recommendedChipLoadInch: [0.002, 0.0045],
    recommendedFeedTurningMm: [0.28, 0.09],
    hardnessTypical: '180-220 HB',
    chipCharacteristics: 'Excelente maquinabilidad, viruta controlable con insertos estándar P25.',
  },
  {
    id: 'tool_steel_d2',
    name: 'Acero para Herramientas D2 (Recocido)',
    category: 'Aceros para Troqueles',
    group: 'P',
    description: 'Alto cromo / alto carbón para punzones, dados y matrices de troquelado.',
    vcTurningMMin: [90, 150],
    sfmMilling: [120, 220],
    kc: 2400,
    recommendedChipLoadInch: [0.0015, 0.003],
    recommendedFeedTurningMm: [0.18, 0.06],
    hardnessTypical: '210-250 HB (Recocido)',
    chipCharacteristics: 'Muy abrasivo por carburos de cromo. Requiere insertos recubiertos AlTiN o PVD tenaz.',
  },
  {
    id: 'tool_steel_d2_hardened',
    name: 'Acero D2 Templado (>55 HRC)',
    category: 'Aceros Templados / Duros',
    group: 'H',
    description: 'D2 templado después de tratamiento térmico. Maquinado duro (Hard Turning / Milling).',
    vcTurningMMin: [50, 100],
    sfmMilling: [60, 150],
    kc: 4500,
    recommendedChipLoadInch: [0.0008, 0.002],
    recommendedFeedTurningMm: [0.10, 0.04],
    hardnessTypical: '58-62 HRC',
    chipCharacteristics: 'Micro-astillado en caliente. Usar insertos CBN (Borazón) o carburo micrograno nACo.',
  },
  {
    id: 'stainless_304',
    name: 'Acero Inoxidable Austenítico 304 / 304L',
    category: 'Aceros Inoxidables',
    group: 'M',
    description: 'Inoxidable de uso general en grado alimenticio, farmacéutico y automotriz.',
    vcTurningMMin: [120, 200],
    sfmMilling: [150, 300],
    kc: 2500,
    recommendedChipLoadInch: [0.0015, 0.0035],
    recommendedFeedTurningMm: [0.20, 0.06],
    hardnessTypical: '160-200 HB',
    chipCharacteristics: 'Endurecimiento por deformación (Work Hardening). Mantener avance continuo; NUNCA frotar.',
  },
  {
    id: 'stainless_316',
    name: 'Acero Inoxidable 316 / 316L (Molibdeno)',
    category: 'Aceros Inoxidables',
    group: 'M',
    description: 'Inoxidable marino y químico con mayor resistencia a la corrosión y alta viscosidad.',
    vcTurningMMin: [100, 180],
    sfmMilling: [120, 260],
    kc: 2600,
    recommendedChipLoadInch: [0.0012, 0.003],
    recommendedFeedTurningMm: [0.18, 0.06],
    hardnessTypical: '170-210 HB',
    chipCharacteristics: 'Más gomoso y abrasivo que 304. Usar refrigerante a alta presión e insertos M20 PVD.',
  },
  {
    id: 'stainless_416',
    name: 'Acero Inoxidable 416 (Corte Libre)',
    category: 'Aceros Inoxidables Martensíticos',
    group: 'M',
    description: 'Inoxidable con azufre añadido para alta maquinabilidad en tornos CNC.',
    vcTurningMMin: [180, 280],
    sfmMilling: [300, 500],
    kc: 2000,
    recommendedChipLoadInch: [0.002, 0.0045],
    recommendedFeedTurningMm: [0.25, 0.08],
    hardnessTypical: '180-240 HB',
    chipCharacteristics: 'Viruta corta y quebradiza, excelente acabado superficial.',
  },
  {
    id: 'aluminum_6061',
    name: 'Aluminio 6061-T6 (Estructural)',
    category: 'Aluminio y Aleaciones Ligeras',
    group: 'N',
    description: 'La aleación de aluminio más popular para piezas maquinadas CNC, placas y carcasas.',
    vcTurningMMin: [350, 800],
    sfmMilling: [800, 2500],
    kc: 700,
    recommendedChipLoadInch: [0.003, 0.008],
    recommendedFeedTurningMm: [0.35, 0.10],
    hardnessTypical: '95 HB',
    chipCharacteristics: 'Corte ultra rápido. Usar insertos pulidos (filo espejo) sin recubrimiento o DLC para evitar adhesión.',
  },
  {
    id: 'aluminum_7075',
    name: 'Aluminio 7075-T6 (Aeroespacial)',
    category: 'Aluminio y Aleaciones Ligeras',
    group: 'N',
    description: 'Aleación con zinc de alta resistencia mecánica similar a aceros estructurales.',
    vcTurningMMin: [300, 700],
    sfmMilling: [700, 2000],
    kc: 850,
    recommendedChipLoadInch: [0.003, 0.007],
    recommendedFeedTurningMm: [0.30, 0.09],
    hardnessTypical: '150 HB',
    chipCharacteristics: 'Viruta más fragmentada que 6061. Excelente acabado superficial.',
  },
  {
    id: 'brass_360',
    name: 'Latón C360 (Free-Cutting Brass)',
    category: 'Cobre y No Ferrosos',
    group: 'N',
    description: 'El metal de mayor maquinabilidad industrial (100% machinability rating).',
    vcTurningMMin: [250, 500],
    sfmMilling: [600, 1500],
    kc: 800,
    recommendedChipLoadInch: [0.003, 0.006],
    recommendedFeedTurningMm: [0.30, 0.08],
    hardnessTypical: '60-80 HRB',
    chipCharacteristics: 'Viruta en polvo o fragmentos minúsculos. Excelente para producción masiva.',
  },
  {
    id: 'cast_iron_gray',
    name: 'Hierro Gris Clase 30 / 40',
    category: 'Fundiciones',
    group: 'K',
    description: 'Fundición para blocks de motor, bancadas, poleas y bases antivibración.',
    vcTurningMMin: [160, 280],
    sfmMilling: [250, 500],
    kc: 1100,
    recommendedChipLoadInch: [0.002, 0.005],
    recommendedFeedTurningMm: [0.30, 0.10],
    hardnessTypical: '180-240 HB',
    chipCharacteristics: 'Polvo y viruta desmenuzada abrasiva. Corte preferiblemente en seco o aire para evitar pasta.',
  },
  {
    id: 'titanium_6al4v',
    name: 'Titanio Grado 5 (Ti-6Al-4V)',
    category: 'Superaleaciones / Titanio',
    group: 'S',
    description: 'Titanio aeroespacial y médico de alta resistencia y baja conductividad térmica.',
    vcTurningMMin: [40, 80],
    sfmMilling: [80, 180],
    kc: 1400,
    recommendedChipLoadInch: [0.001, 0.0025],
    recommendedFeedTurningMm: [0.15, 0.05],
    hardnessTypical: '32-38 HRC',
    chipCharacteristics: 'Concentra todo el calor en la punta del filo. Usar refrigerante abundante a alta presión.',
  },
  {
    id: 'delrin_acetal',
    name: 'Plástico de Ingeniería Delrin / Acetal',
    category: 'Plásticos y Polímeros',
    group: 'N',
    description: 'Termoplástico rígido de bajo rozamiento para engranes, bujes aislantes y fixtures.',
    vcTurningMMin: [200, 450],
    sfmMilling: [500, 1200],
    kc: 350,
    recommendedChipLoadInch: [0.004, 0.010],
    recommendedFeedTurningMm: [0.35, 0.12],
    hardnessTypical: '85 Rockwell M',
    chipCharacteristics: 'Viruta en cinta continua. Requiere filos ultra afilados sin recubrimiento para evitar rebaba.',
  }
];

export function findMaterialById(id: string): MaterialSpec | undefined {
  return MATERIAL_DATABASE.find(m => m.id === id);
}

export function findMaterialByQuery(query: string): MaterialSpec | undefined {
  const q = query.toLowerCase().trim();
  if (!q) return undefined;
  return MATERIAL_DATABASE.find(m =>
    m.id.toLowerCase().includes(q) ||
    m.name.toLowerCase().includes(q) ||
    m.category.toLowerCase().includes(q) ||
    m.description.toLowerCase().includes(q)
  );
}
